Switch to master before deleting the branch we created
If we don't we get this:

    [DZ] all's well; removing .build/kncvxDic6d
    error: Cannot delete the branch 'buildkite/37cd95135aec3e2aa6f212cd7c4dd77bb17e19fd' which you are currently on.